name: Exercice Variables

on: [push]

env:
  MON_NOM: "khelas"
  MA_VILLE: "constantine"

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps:
    - name: Dire qui je suis
      run: |
        echo "Je m'appelle $MON_NOM"
        echo "J'habite Ã  $MA_VILLE"
        echo "Date du jour : $(date)"